/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ryandens.javaaagent.example.java-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("com.ryandens.javaaagent.example.App")
}
