name: "Publish release"

on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2.11.0
        with:
          cache-read-only: false

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Publish release to Gradle Plugin Portal
        run: "./gradlew publishPlugins --no-configuration-cache"
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
